import type { NextPage } from 'next'
import Head from 'next/head'

import { Main } from '@containers/Main'
import styled from 'styled-components'

const Container = styled.div`
  background-color: var(--base-dark-bg1);
  margin: 0;
  padding: 0;
  width: 100%;
  min-height: 100vh;
  display: flex;
  justify-content: center;
  align-items: center;
`

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
          crossOrigin=''
        />
        <link
          href='https://fonts.googleapis.com/css2?family=Barlow:wght@300;400;500;600;700&display=swap'
          rel='stylesheet'
        />
      </Head>

      <Container>
        <Main />
      </Container>
    </div>
  )
}

export default Home
